// Composition of small canonical sources into large target files. Pure: takes
// data, returns strings. The ONLY templating is the placeholder set below — a
// rule that uses anything else fails loudly at emit time.
import { ROOT_SECTIONS } from "./canonical.mjs";

export const SECTION_TITLES = Object.freeze({
  answer: "The two questions",
  tiers: "Autonomy tiers",
  "oracle-integrity": "Oracle integrity",
  "change-control": "Change control",
  session: "Session protocol",
  dispatch: "Roles and dispatch",
  knowledge: "Knowledge",
  ledger: "Ledger",
  evidence: "Evidence",
  enforcement: "Enforcement: intended vs declared actual",
});

export const PLACEHOLDERS = Object.freeze([
  "product.name",
  "product.summary",
  "policy.tier1-paths",
  "policy.gated-paths",
  "policy.approver",
  "oracles.table",
  "knowledge.index",
  "release.integration-branch",
  "roles.location",
  "dispatch.map",
  "enforcement.table",
]);

/** @param {string[]} items @param {string} empty */
function bullets(items, empty) {
  return items.length ? items.map((i) => `- \`${i}\``).join("\n") : `- ${empty}`;
}

/**
 * @param {Array<{ id: string, argv: string[], cwd: string, kind: string, direction?: string, title: string }>} oracles
 */
export function renderOraclesTable(oracles) {
  if (!oracles.length) return "_No oracles detected. Declare them in `sisu.yaml` (`custom-oracles:`) — a project with no oracle has no safety net to protect._";
  const rows = oracles.map((o) => `| \`${o.id}\` | \`${o.argv.join(" ")}\`${o.cwd !== "." ? ` (in \`${o.cwd}\`)` : ""} | ${o.kind === "ratchet" ? `ratchet (${o.direction})` : "invariant"} |`);
  return ["| oracle | command | kind |", "|---|---|---|", ...rows, "", "Ratchets: `node harness/scripts/ratchet.mjs` (all metrics; prints the new number when debt drops)."].join("\n");
}

/**
 * @param {Array<{ name: string, dispatch: string }>} roles @param {string} location
 */
export function renderDispatchMap(roles, location) {
  return roles
    .slice()
    .sort((a, b) => (a.name < b.name ? -1 : 1))
    .map((r) => `- ${r.dispatch} → \`${r.name}\` (\`${location}/${r.name}.md\`)`)
    .join("\n");
}

/**
 * @param {Array<{ id: string, title: string, lifecycle: string, intended: { effect: string, plane: string, bypassableBy: string, failMode: string }, state: string, reason: string | null }>} rows
 */
export function renderEnforcementTable(rows) {
  const head = ["| mechanism | intended | plane | bypassable by | fail-mode | state |", "|---|---|---|---|---|---|"];
  const body = rows.map((r) => {
    const state = r.state === "installed" ? "installed" : `${r.state}${r.reason ? ` — ${r.reason}` : ""}`;
    const lc = r.lifecycle === "stable" ? "" : ` _(${r.lifecycle})_`;
    return `| \`${r.id}\`${lc} | ${r.intended.effect} | ${r.intended.plane} | ${r.intended.bypassableBy} | ${r.intended.failMode} | ${state} |`;
  });
  return [...head, ...body].join("\n");
}

/**
 * Fill placeholders. Unknown placeholders throw.
 * @param {string} text @param {Record<string, string>} values
 */
export function fill(text, values) {
  return text.replace(/\{\{([a-z0-9.-]+)\}\}/g, (_, key) => {
    if (!PLACEHOLDERS.includes(key)) throw new Error(`unknown placeholder {{${key}}}`);
    if (!(key in values)) throw new Error(`placeholder {{${key}}} has no value`);
    return values[key];
  });
}

/**
 * Compose the root convention file for a target.
 * @param {{
 *   target: string,
 *   rules: Array<{ id: string, title: string, section: string, order: number, targets: string[], body: string, enforcedBy: string[] }>,
 *   mechanisms: Array<{ id: string, intended: { effect: string, plane: string, bypassableBy: string }, state: string }>,
 *   values: Record<string, string>,
 *   preamble: string,
 * }} input
 * @returns {{ content: string, composedFrom: string[] }}
 */
export function composeRoot(input) {
  const composedFrom = [];
  const byId = new Map(input.mechanisms.map((m) => [m.id, m]));
  const out = [];
  out.push(`# ${input.values["product.name"]} — agent conventions`);
  out.push("");
  out.push("<!-- GENERATED by sisu from canonical sources. Do not edit: customize through overrides/ and re-emit.");
  out.push("     Composition is recorded in sisu.lock.json. Everything here is convention; the enforcement table");
  out.push("     at the end says which conventions are walls, and against whom. -->");
  out.push("");
  out.push(`> ${input.values["product.summary"]}`);
  if (input.preamble) {
    out.push("");
    out.push(input.preamble.trim());
  }
  for (const section of ROOT_SECTIONS) {
    const rules = input.rules.filter((r) => r.section === section && r.targets.includes(input.target)).sort((a, b) => a.order - b.order || (a.id < b.id ? -1 : 1));
    if (!rules.length) continue;
    out.push("");
    out.push(`## ${SECTION_TITLES[section]}`);
    for (const r of rules) {
      composedFrom.push(`canonical/rules/${r.id}.md`);
      out.push("");
      out.push(fill(r.body.trim(), input.values));
      const enforcers = r.enforcedBy.flatMap((id) => {
        const m = byId.get(id);
        return m ? [m] : [];
      });
      if (enforcers.length) {
        out.push("");
        out.push(
          "_Enforced by:_ " +
            enforcers
              .map((m) => `\`${m.id}\` (${m.intended.effect}, ${m.intended.plane}, bypassable by ${m.intended.bypassableBy}${m.state !== "installed" ? `, **${m.state}**` : ""})`)
              .join(" · "),
        );
      }
    }
  }
  out.push("");
  return { content: out.join("\n").replace(/\n{3,}/g, "\n\n") + "", composedFrom };
}

/** Byte length of UTF-8 text. */
export function byteLength(s) {
  return Buffer.byteLength(s, "utf8");
}
