// CODEOWNERS provisioning. Emitted only for GitHub hosts and only when the file
// did not pre-exist (shared-file rule). When no host-verified approver is known,
// the owner column is left as a commented TODO: an owner without write access is
// silently ignored by GitHub, and a made-up handle would LOOK configured while
// enforcing nothing — doctor's favourite meal.
export const CODEOWNERS_PATH = ".github/CODEOWNERS";

/**
 * @param {{ approver: string | null, tier1Paths: string[], gateDefinitionPaths: string[], ownedPaths: string[] }} input
 */
export function renderCodeowners(input) {
  const owner = input.approver;
  const L = [];
  L.push("# GENERATED by sisu — the single source of truth for gated paths. Do not copy this list into docs.");
  L.push("# Code-owner review enforces ONLY when: the host rule 'require review from code owners' is on,");
  L.push("# the owner has write access, this file is under 3 MB with no invalid line, and the agent identity");
  L.push("# cannot self-approve. `sisu doctor --remote` probes each of those silent-failure shapes.");
  L.push("# Last matching pattern wins.");
  if (!owner) {
    L.push("#");
    L.push("# TODO: no host-verified approver yet (sisu.yaml policy.approver is null). Every line below is");
    L.push("# commented out so this file is valid-but-empty and HONEST: it enforces nothing until an approver");
    L.push("# is set. Set `policy.approver: \"@handle\"` and re-emit.");
  }
  const line = (p) => (owner ? `${p.padEnd(44)} ${owner}` : `# ${p.padEnd(42)} @TODO-approver`);
  L.push("");
  L.push("# --- harness, control files and this file ---");
  for (const p of input.ownedPaths) L.push(line(p));
  L.push(line("/.github/CODEOWNERS"));
  if (input.gateDefinitionPaths.length) {
    L.push("");
    L.push("# --- gate definitions (an agent that can edit these can relax a gate and self-merge) ---");
    for (const p of input.gateDefinitionPaths) L.push(line(p));
  }
  if (input.tier1Paths.length) {
    L.push("");
    L.push("# --- project Tier-1 paths (sisu.yaml policy.tier1-paths) ---");
    for (const p of input.tier1Paths) L.push(line(p));
  }
  L.push("");
  return L.join("\n");
}

/** Owned/gated paths in CODEOWNERS syntax (leading slash = repo-root anchored). */
export function ownedGatedPaths() {
  return ["/sisu.yaml", "/sisu.lock.json", "/harness/", "/overrides/", "/CLAUDE.md", "/AGENTS.md", "/.claude/", "/.github/", "/project/quality-baselines.json", "/project/waivers/", "/project/roles/"];
}

/** @param {string} p */
export function toCodeownersPattern(p) {
  if (p.startsWith("/")) return p;
  if (p.includes("*")) return p; // glob: unanchored is fine
  return "/" + p;
}
