// Role emission. Canonical roles declare CAPABILITIES; the emitter translates
// them into each target's allow/deny lists using committed target constants.
// Every restricted role gets its restricting fields written explicitly, because
// for Claude Code a missing `tools` key means "inherit everything".
import { joinFrontmatter } from "../../assets/lib/frontmatter.mjs";
import { TARGETS } from "../targets.mjs";
import { CAPABILITIES } from "../canonical.mjs";

/**
 * @param {{ name: string, title: string, description: string, capabilities: string[], model: string, body: string, source: string }} role
 * @returns {{ path: string, content: string, frontmatter: Record<string, unknown> }}
 */
export function renderClaudeAgent(role) {
  const t = TARGETS["claude-code"];
  const tools = new Set();
  for (const cap of role.capabilities) for (const tool of t.capabilityTools[cap] ?? []) tools.add(tool);
  const denies = new Set();
  for (const cap of CAPABILITIES) {
    if (!role.capabilities.includes(cap)) for (const tool of t.capabilityDenies[cap] ?? []) denies.add(tool);
  }
  /** @type {Record<string, unknown>} */
  const fm = {
    name: role.name,
    description: role.description,
    model: t.modelTier[role.model],
    tools: [...tools].join(", "),
  };
  if (denies.size) fm.disallowedTools = [...denies].join(", ");
  const body = `${role.body.trim()}\n\n<!-- generated by sisu from ${role.source}; capabilities: ${role.capabilities.join(", ")} -->\n`;
  return { path: `${t.agentsDir}/${role.name}.md`, content: joinFrontmatter(fm, body), frontmatter: fm };
}

/**
 * Portable role file for the agents-md fallback: canonical frontmatter kept, so
 * any tool (or a human) can read it; nothing here is tool-specific.
 * @param {{ name: string, title: string, description: string, capabilities: string[], model: string, body: string, source: string, dispatch: string }} role
 */
export function renderPortableRole(role) {
  const t = TARGETS["agents-md"];
  const fm = {
    name: role.name,
    title: role.title,
    description: role.description,
    capabilities: role.capabilities,
    model: role.model,
    dispatch: role.dispatch,
  };
  const body = `${role.body.trim()}\n\n<!-- generated by sisu from ${role.source} -->\n`;
  return { path: `${t.rolesDir}/${role.name}.md`, content: joinFrontmatter(fm, body) };
}

/**
 * Claude Code settings.json with hook wiring. Hooks are emitted scripts under
 * harness/agent-hooks/, invoked through the project-dir env var so the path is
 * stable across clones.
 * @param {{ hooks: string[] }} input list of hook script basenames to wire
 */
export function renderClaudeSettings(input) {
  const t = TARGETS["claude-code"];
  const cmd = (file) => `node "$${t.projectDirEnv}/harness/agent-hooks/${file}"`;
  const has = (f) => input.hooks.includes(f);
  /** @type {Record<string, any>} */
  const hooks = {};
  const pre = [];
  const bashHooks = ["deny-tier0.mjs", "verification-gate.mjs"].filter(has).map((f) => ({ type: "command", command: cmd(f) }));
  if (bashHooks.length) pre.push({ matcher: "Bash", hooks: bashHooks });
  if (has("protect-owned-paths.mjs")) pre.push({ matcher: "Edit|Write|MultiEdit|NotebookEdit", hooks: [{ type: "command", command: cmd("protect-owned-paths.mjs") }] });
  if (pre.length) hooks.PreToolUse = pre;
  if (has("session-start.mjs")) hooks.SessionStart = [{ hooks: [{ type: "command", command: cmd("session-start.mjs") }] }];
  const settings = {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    hooks,
  };
  return JSON.stringify(settings, null, 2) + "\n";
}
