// Renders the emitted GitHub Actions workflow. Pure function of the graph
// inputs. Mechanics it must respect (verified against GitHub docs 2026-08-21):
// a job-level `if:` skip reports SUCCESS and satisfies a required check, a
// workflow-level path filter leaves it PENDING; aggregators run under always()
// and inspect needs.*.result explicitly; required workflows declare merge_group;
// third-party actions are pinned to full SHAs.
import { ACTION_PINS, GITLEAKS_VERSION } from "../targets.mjs";

export const WORKFLOW_PATH = ".github/workflows/sisu-gates.yml";
export const REQUIRED_CHECK_NAME = "sisu / verdict";
export const CHANGE_SCAN_NAME = "sisu / change scan";
export const GATES_NAME = "sisu / gates";

/** Paths that are NEVER "just docs": the governance carve-out, checked before the docs allowlist. */
export const GOVERNANCE_PATTERNS = ["CLAUDE.md", "*/CLAUDE.md", "AGENTS.md", ".claude/*", "harness/*", "sisu.yaml", "sisu.lock.json", ".github/*", "overrides/*", "project/quality-baselines.json", "project/waivers/*", "project/roles/*", ".gitleaks.toml", "package-lock.json", "*/package-lock.json"];

/** @param {string} name */
function pin(name) {
  const p = ACTION_PINS[name];
  if (!p) throw new Error(`no pin for action ${name}`);
  return `${name}@${p.sha} # ${p.tag}`;
}

/** @param {string} s */
function yq(s) {
  return JSON.stringify(s);
}

/**
 * @param {{
 *   branches: string[],
 *   packs: Array<{ id: string, ci: { setup: string, installArgv: string[] | null, versionFile?: string } }>,
 *   oracles: Array<{ id: string, title: string, kind: string, argv: string[], cwd: string }>,
 *   hasRatchets: boolean,
 *   hasAgentHooks: boolean,
 * }} input
 */
export function renderWorkflow(input) {
  const L = [];
  const push = (s = "") => L.push(s);
  push("# GENERATED by sisu — do not edit; customize via overrides/ and re-emit.");
  push("# The required status check for protected branches is the job named");
  push(`# ${yq(REQUIRED_CHECK_NAME)}. It runs under always() and never skips, so a skipped`);
  push("# upstream job can never be mistaken for a satisfied required check.");
  push("name: sisu gates");
  push("");
  push("on:");
  push("  pull_request:");
  push(`    branches: [${input.branches.map(yq).join(", ")}]`);
  push("  merge_group:");
  push("  workflow_dispatch:");
  push("");
  push("permissions:");
  push("  contents: read");
  push("");
  push("concurrency:");
  push("  group: sisu-gates-${{ github.event.pull_request.number || github.ref }}");
  push("  cancel-in-progress: true");
  push("");
  push("jobs:");
  // ---- change scan (always on)
  push("  change-scan:");
  push(`    name: ${yq(CHANGE_SCAN_NAME)}`);
  push("    runs-on: ubuntu-latest");
  push("    timeout-minutes: 5");
  push("    outputs:");
  push("      docs_only: ${{ steps.classify.outputs.docs_only }}");
  push("    steps:");
  push(`      - uses: ${pin("actions/checkout")}`);
  push("        with:");
  push("          fetch-depth: 2");
  push("      - name: Secret scan (always-on copy)");
  push("        run: |");
  push(`          GL=${GITLEAKS_VERSION}`);
  push("          curl -sSfL \"https://github.com/gitleaks/gitleaks/releases/download/v${GL}/gitleaks_${GL}_linux_x64.tar.gz\" | tar -xz gitleaks");
  push("          ./gitleaks detect --no-git --redact --no-banner --exit-code 1");
  push("      - name: Classify diff (docs-only? fail-safe toward running)");
  push("        id: classify");
  push("        run: |");
  push("          set -euo pipefail");
  push("          DOCS_ONLY=false");
  push("          FILES=\"\"");
  push("          if [[ \"${{ github.event_name }}\" == \"pull_request\" ]]; then");
  push("            if FILES=$(git diff --name-only HEAD^1 HEAD) && [[ -n \"$FILES\" ]]; then");
  push("              DOCS_ONLY=true");
  push("              while IFS= read -r f; do");
  push("                case \"$f\" in");
  push("                  # governance is never docs — checked BEFORE the docs allowlist");
  push(`                  ${GOVERNANCE_PATTERNS.join("|")})`);
  push("                    DOCS_ONLY=false; break ;;");
  push("                  docs/*|*.md) ;;");
  push("                  *) DOCS_ONLY=false; break ;;");
  push("                esac");
  push("              done <<< \"$FILES\"");
  push("            fi");
  push("          fi");
  push("          echo \"docs_only=$DOCS_ONLY\" >> \"$GITHUB_OUTPUT\"");
  push("          echo \"docs_only=$DOCS_ONLY\"");
  push("");
  // ---- gates (heavy)
  push("  gates:");
  push(`    name: ${yq(GATES_NAME)}`);
  push("    runs-on: ubuntu-latest");
  push("    timeout-minutes: 30");
  push("    needs: [change-scan]");
  push("    # Skips ONLY on a proven docs-only diff. A failed/errored scan un-skips.");
  push("    if: ${{ always() && (needs.change-scan.result != 'success' || needs.change-scan.outputs.docs_only != 'true') }}");
  push("    steps:");
  push(`      - uses: ${pin("actions/checkout")}`);
  // maintenance runtime is always Node
  push(`      - uses: ${pin("actions/setup-node")}`);
  push("        with:");
  push("          node-version: 20");
  for (const p of input.packs) {
    if (p.ci.setup === "python") {
      push(`      - uses: ${pin("actions/setup-python")}`);
      push("        with:");
      push("          python-version: \"3.12\"");
      push("      - name: Install Python project");
      push("        run: |");
      push("          python -m pip install --upgrade pip");
      push("          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi");
      push("          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi");
      push("          if [ -f pyproject.toml ]; then pip install -e . || true; fi");
    }
    if (p.ci.installArgv) {
      push(`      - name: Install (${p.id})`);
      push(`        run: ${p.ci.installArgv.join(" ")}`);
    }
  }
  push("      - name: Secret scan (required-check copy)");
  push("        run: |");
  push(`          GL=${GITLEAKS_VERSION}`);
  push("          curl -sSfL \"https://github.com/gitleaks/gitleaks/releases/download/v${GL}/gitleaks_${GL}_linux_x64.tar.gz\" | tar -xz gitleaks");
  push("          ./gitleaks detect --no-git --redact --no-banner --exit-code 1");
  push("      - name: Harness self-verification (roles load, refs resolve, dispatch complete, hooks behave)");
  push("        run: node --test \"harness/tests/*.test.mjs\"");
  push("      - name: Knowledge index within budget and active facts meet the promotion bar");
  push("        run: node harness/scripts/index.mjs --check");
  if (input.hasRatchets) {
    push("      - name: Ratchets (ceilings only fall, floors only rise, identities bound, waivers unexpired)");
    push("        run: node harness/scripts/ratchet.mjs");
  }
  for (const o of input.oracles.filter((x) => x.kind === "invariant")) {
    push(`      - name: ${yq(`Oracle ${o.id} — ${o.title}`)}`);
    if (o.cwd && o.cwd !== ".") push(`        working-directory: ${yq(o.cwd)}`);
    push(`        run: ${o.argv.map((a) => (/[\s"'$]/.test(a) ? yq(a) : a)).join(" ")}`);
  }
  push("");
  // ---- verdict (THE required check)
  push("  verdict:");
  push(`    name: ${yq(REQUIRED_CHECK_NAME)}`);
  push("    runs-on: ubuntu-latest");
  push("    timeout-minutes: 5");
  push("    needs: [change-scan, gates]");
  push("    # always(): a failed upstream job must produce a RED required check, never a skipped one.");
  push("    if: ${{ always() }}");
  push("    steps:");
  push("      - name: Verdict (red unless gates succeeded, or were skipped by a PROVEN docs-only diff)");
  push("        env:");
  push("          SCAN_RESULT: ${{ needs.change-scan.result }}");
  push("          GATES_RESULT: ${{ needs.gates.result }}");
  push("          DOCS_ONLY: ${{ needs.change-scan.outputs.docs_only }}");
  push("        run: |");
  push("          echo \"scan=$SCAN_RESULT gates=$GATES_RESULT docs_only=$DOCS_ONLY\"");
  push("          if [ \"$GATES_RESULT\" = \"success\" ]; then exit 0; fi");
  push("          if [ \"$GATES_RESULT\" = \"skipped\" ] && [ \"$SCAN_RESULT\" = \"success\" ] && [ \"$DOCS_ONLY\" = \"true\" ]; then");
  push("            echo \"docs-only diff: heavy gates skipped by design (skipped counts as satisfied HERE ONLY)\"; exit 0");
  push("          fi");
  push("          echo \"::error::gates result: $GATES_RESULT (scan: $SCAN_RESULT)\"; exit 1");
  push("");
  return L.join("\n");
}
